name: CD PipeLine

on:
  workflow_run: 
    workflows: ["CI Pipeline"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull Docker Image
        run: sudo docker pull saimadan82/loanprediction:latest
      - name: Delete Old Docker Image
        run: sudo docker rm -f loanprediction-container || true

      - name: Run Docker Container
        run: sudo docker run -it -d -p 8001:8001 --name loanprediction-container saimadan82/loanprediction:latest
