name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements/requirements.txt

      - name: Train Model
        run: python loanprediction/train_pipeline.py

      - name: Install Test Dependencies
        run: pip install -r requirements/test_requirements.txt

      - name: Test Model
        run: pytest

      - name: Install Build Dependencies
        run: pip install build

      - name: Build Package
        run: |
          python -m build
          mv dist/*.whl .

      - name: Install FastAPI Dependencies
        run: pip install -r loanprediction_api/requirements.txt

      - name: Start FastAPI (Test Only)
        run: python loanprediction_api/app/main.py &

  docker-build-push:
    needs: build-train-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'saimadan82'
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: saimadan82/loanprediction:latest 
